### ISSUE TITLE
Remove BLOB support

### ISSUE THREAD

**Issue by RomanMeingassner** [crate/crate#11108]
**Feature description**:
We will remove the official BLOB support from Crate. There are several resons that made us take this decision.
Some of the major issues we have with BLOB: 

- CrateDB doesnt have a built in backup solution for BLOB data
- Apparently it is not used a lot (by our none customers & users)
- It needs to be maintained and code has to be adopted
- PostgreSQL clients have no interface to utilize BLOBs

The plan is to first deprecate the BLOB support most likely in version 4.5. Final removal will probably happen with the next major version update (5.0) somewhen later this year.  

If you are looking for an alternative to BLOB storage e.g. https://min.io/ is a viable solution that can be used in combination with CrateDB.

---

- Deprecation in 4.x
- Removal in 5.0 

Issues about blobs:

- [Blobs without sha hash](https://github.com/crate/crate/issues/2981)
- [copy from/to local blob storage](https://github.com/crate/crate/issues/1378)
- [Blob table backups](https://github.com/crate/crate/issues/5939)
- [Object name for blob table](https://github.com/crate/crate/issues/6471)
- [CREATE BLOB TABLE IF NOT EXISTS table_name](https://github.com/crate/crate/issues/9241)

**Comment by MikeMaxFR** [comment]
Ouch... Blobs tables are used in production on my side since a long time.. which works really fine. 
And I implemented it in my CrateDBAdmin client to promote it on usage.

I’m crying...

**Comment by proddata** [comment]
> - PostgreSQL clients have no interface to utilize BLOBs

PostgreSQL clients don't have an interface to use BLOBs wit CrateDB. In general PostgreSQL and client support binary formats also e.g. with the lo_ module.

**Comment by mfussenegger** [comment]
Thank you @MikeMaxFR for the inputs.

Part of the reason we opened up this issue early is so that users like you still have the opportunity to give feedback.


> Each FS on a production environment must have a backup. For CrateDB node or anything else.

Not necessarily. We often see the pattern that customers distinguish between data (which of course requires a backup) and configuration. The configuration is managed by another system (Salt, Ansible or similar - also with backups).

Say you manage a CrateDB node via Ansible, then the only production data is within the tables of the cluster. In such a scenario you can use the snapshot functionality for the backups and don't need any additional FS backup mechanism. It's actually not really supported to use FS level snapshotting or rsync functionality to backup non-blob tables.

If you use the blob feature additionally, you'd have to have two solutions: Backups for blobs via FS, Backups for regular user tables via snapshots. That's not an ideal experience.



> Not a lot but it should be more used with easier usage maybe ! ;)


True, but we have to set priorities. See last answer


> PostgreSQL clients have no interface to utilize BLOBs <= i don't use PostgreSQL Clients, i'm using CrateDBAdmin.net Client, which can manage blobs with preview ;)


From the perspective of a user who favors a PostgreSQL client, having to add a second client to utilize the blob feature is not ideal. See also my next answer.


> It needs to be maintained and code has to be adopted <= ..as every feature :)


True, but everything that has to be maintained has an ongoing opportunity cost. What *aren't* we taking care of while we're busy maintaining a feature. Sometimes a feature can even prevent us from building another, maybe more useful feature, or at least make it more difficult to build.


Blobs were one of the first features and over time the market for CrateDB became more clear and the product vision also evolved. We now have a couple of "core pillars" or product principles that are used as sanity check when we add new features. Two of which are "SQL Standard" and "PostgreSQL compatibility". Blob support doesn't fit into that in it's current form. It's a bit like having two separate products within the same distribution.

There would be another option beside removing it: Integrate it better. But that requires work, and we saw little demand, so it's difficult for us to justify putting work into this.
There are also some issues with the implementation that limit the scalability (Some operations block on the transport thread).


That said. CrateDB is open source, and open for contributions. There are several options:

- Somebody could step up and help maintain it
- A customer could put $$ behind it to help fund ongoing maintenance
- We could consider alternative integrations or features that would cover your use case.
  - For example we're currently considering adding a binary data type that is suited for *small* payloads and can be used in columns of regular tables. Could you elaborate a bit more on your use case? What data are you storing?

**Comment by MikeMaxFR** [comment]
Hello,

I'm not convinced of your argument about adapting (or rather constraining) to PostgreSQL compatibility at the expense of a feature that seemed promising if it had been maybe better promoted among users (and that was already very useful for my company in its current version).

In my case I use blobs for few millions of "small" files like PDFs indeed (order forms, delivery notes, Image Logos, etc..) and also for mail and private messages attachments (we can have bigger files on this (15/20MB)), but a potential size limit in the management of a binary type could be more limiting than blobs. But it would be better than nothing (what would be the maximum size of a binary entry ?).

Too bad that we can only do "better than nothing".

But keep up the good work for SQL Standard , it already works very well :)... For PostgreSQL, i still consider that is another product and it blurs the identity of the CrateDB product (i see the interest of an easy compatibility to attract PostGreSQL users, but SQL Standard seems to me to be enough, especially if you lose time by forsaking other features especially for those who have no special interest to use PostGreSQL compatibility).

**Comment by seut** [comment]
After some more (internal) discussion, we've decided to **NOT** remove the BLOB support by now. 
We agree about the use-case of storing large binary objects and planning to come up with a SQL based implementation (e.g. BLOB data type) in future which should then also support backup & restore of these binary objects (no ETA at all).
Until we or a contributor can provide such an alternative solution for storing BLOBs, we do not plan to change or remove the current implementation.

But please be aware that until such a solution is implemented we probably won't add the missing backup & restore support to the current implementation.
