### ISSUE TITLE
Big partitioned table isn't recovering on 4.6.3 on k8s cluster.

### ISSUE THREAD

**Issue by rjbaat** [crate/crate#11756]
### CrateDB version

4.6.3

### CrateDB setup information

3 node crate 4.6.3 cluster on k8s with 6g heap size and a table with 900 million records partitioned per week with 12 shards and 1 replica. 

### Steps to Reproduce

I upgraded from 4.6.1 to 4.6.3 by bringing the 3 pods down. Then adjusting the yaml and bringing the cluster up again. That went fine, all is starting and most tables in db are recovering fine. But the big table isn't. The table is partly recovering. The oldest partitions are stated critical and won't recovering, while others turn green. Crate is saying the total of the amount of records in the table are 760 million instead of the 910 million it should have. I don't understand, because there must be at least 1 replica on one of the nodes, but it seams to be lost because its staying critical. The only thing I can do is restore the whole table from a snapshot now. This is happend me before also on 4.6.1. So I think somehow big tables are hard to recover. Didn't have problem this on older cratedb versions.

### Expected Result

I expect it to rebuild the table fine. because it was green before the cluster was downnscaled to 0 and there was a replica in place. 

### Actual Result

Not sure where to find the logs.

**Comment by mfussenegger** [comment]
Could you check and share the output of the `sys.allocations` table? The output might contain some explanations why the shards aren't recovering

**Comment by rjbaat** [comment]
Thnx for the reply! I had to restore the table, but lost some partitions :(. Somehow rebuilding isn't very stable even if there are replicas in place on multiple nodes. Next time it will happen I will post what the `sys.allocations` show.

**Comment by mfussenegger** [comment]
Sorry to hear that.

The [alter cluster reroute retry failed](https://crate.io/docs/crate/reference/en/4.6/sql/statements/alter-cluster.html?highlight=alter%20cluster#reroute-retry-failed) command usually solves intermediate allocation hiccups.

If it occurs again and that doesn't work, could post the logs? 

If running on k8s, `kubectl logs my-pod` should output them.

**Comment by proddata** [comment]
> But now I am a bit worried what will happen to the crate statefull set that's running on it. Do you have recommendations?

Upgrading is generally should not be a problem if the cluster is shutdown gracefully.
We regularly upgrade clusters with tables with multiple billions of records.

More info on how to plan upgrades can be found here:
https://crate.io/docs/crate/howtos/en/latest/admin/rolling-upgrade.html
https://crate.io/docs/crate/howtos/en/latest/admin/full-restart-upgrade.html

> I am a bit fearsome it will restart all nodes at once and it will not rebuild the entire tables like happend before.

If nodes are terminated the correct way, this should not happen. If yes, then it would be a bug.

> FE, is there a way crate will update the nodes one by one, and watching the state of the whole cluster while rebuilding the tables to keep the data intact before continuing to the next node?

This is part of our managed services (Cloud / Edge) and also available with the k8s operator https://github.com/crate/crate-operator

**Comment by jayeff** [comment]
@rjbaat For future CrateDB cluster upgrades you could alternatively try to use [rolling upgrade](https://crate.io/docs/crate/howtos/en/latest/admin/rolling-upgrade.html) instead of [full cluster restart](https://crate.io/docs/crate/howtos/en/latest/admin/full-restart-upgrade.html).

We do upgrade cluster with bigger tables, so CrateDB should normally be able to recover a table your size without any problem.

> I need to upgrade my k8s cluster. But now I am a bit worried what will happen to the crate statefull set that's running on it. Do you have recommendations?

We do recommend to have working backups in place before upgrading k8s or CrateDB. Unfortunately we cannot help further with custom crate cluster deployments. When using [CrateDB Cloud](https://crate.io/products/cratedb-cloud) such operational concerns are handled by us.

**Comment by rjbaat** [comment]
Hi @jayeff is just upgraded the cluster from 4.6.3 to 4.6.6 with a 3 node cluster with the setting: `recover_after_nodes` = 3 and `expected_nodes` = 3. This went quite good and fast this time. But on the big table I got 2 partitions in critical state and missing data. When I query the table like: `select * from sys.allocations where current_state != 'STARTED' limit 100;` I get a few results saying: 

```
cannot allocate because allocation is not permitted to any of the nodes that hold an in-sync shard copy 
```

and 

```
cannot allocate because allocation is not permitted to any of the nodes
```

Is there a way to get those 2 partitions to become healthy again?

**Comment by seut** [comment]
@rjbaat Are you maybe running into the default 1000 shard limits per node? https://crate.io/docs/crate/reference/en/4.6/config/cluster.html#shard-limits

**Comment by jayeff** [comment]
@rjbaat Did you try to run [`REROUTE RETRY FAILED`](https://crate.io/docs/crate/reference/en/4.6/sql/statements/alter-cluster.html#reroute-retry-failed)?

Also could you provide us the CrateDB logs?

> Is there maybe a way to retrieve only those shards from a snapshot and pulling them back into the table?

It's not possible to retrieve only specific shards. You would need to restore the full partition in this case.

**Comment by rjbaat** [comment]
Hi @seut I counted the shards an I have 1710 shards started on a 3 node cluster. 6 shared are Underreplicated. 

Can I restore the affected partition to the current critical table? so it will overwrite the existing partition and I don't need to swap the complete table?

**Comment by seut** [comment]
@rjbaat Ah sorry, my example was wrong as it did not count per node which the shard limits defines.
So the query should be: `SELECT node['id'], count(*) FROM sys.shards GROUP BY 1;`

But anyway it looks like this is not the issue.

**Comment by rjbaat** [comment]
@seut 
I tried your query and got this results: 

NULL = 6 
node 1 = 573 
node 2 = 569 
node 3 = 568 

So they are well under the 1000 shards per node.

**Comment by rjbaat** [comment]
@seut I picked one of the partition_ident that's affected and get this result. 

```
created: 3.0.1
upgraded: 4.6.3
```

**Comment by rjbaat** [comment]
I see I can only restore the affected partitions from a snapshot without having to drop the entire table. That's awesome and a good way to get the data back. But I would still like to know how to prevent this missing shard problem from happening. so it will not occur with the next upgrade.

**Comment by seut** [comment]
@rjbaat Great to hear that you could restore the affected partitions. We'll investigate this further and probably fix to ensure it won't happen again. Thank you for reporting.

**Comment by rjbaat** [comment]
thnx! i will keep an eye on the new cratedb releases and then see what will happen on the next upgrade.

**Comment by seut** [comment]
@rjbaat We've fixed the issue and will release it with the next 4.6 hotfix version. Thank you again for reporting.

**Comment by rjbaat** [comment]
@seut Cool thnx for the quick fix and for letting me know!

**Comment by rjbaat** [comment]
@seut I just upgraded to 4.6.7 and I still have 6 partitions in critical state. So I have to delete those and restore them from the last snapshot. So I think it's not yet fixed in 4.6.7. I did try agin the `ALTER CLUSTER REROUTE RETRY FAILED` command to see if that made a difference, but no luck for the critical partitions.

**Comment by rjbaat** [comment]
I had to upgrade my k8s cluster and so the crate cluster (4.6.7) needed to be restarted and then the tables to be rebuild.
I ran into the same problem with several partitions not recovering and staying in critical state. This way I again need to restore some critical partitions and can relay on a smooth restart and rebuild of the tables. Not sure why this is. Can it be to the: `routing.allocation.max_retries` set to low?

**Comment by proddata** [comment]
@rjbaat could you check if the checkpoints on your shards are in sync / not stuck

e.g. by:
```sql
SELECT s.table_name,
       s.partition_ident,
       seq_no_stats['global_checkpoint'],
       seq_no_stats['local_checkpoint']
FROM sys.SHARDS s
where  seq_no_stats['global_checkpoint'] <> seq_no_stats['local_checkpoint']
order by 1,2
limit 1000;
```

you might want to run a `REFRESH TABLE` first.

**Comment by rjbaat** [comment]
@proddata Sorry I didn't see the comment.

@seut I just had the same problem again after a restart on the cluster after a resize of volumes.

When I run the suggested query on the cluster I get this result:

table_name | partition_ident | seq_no_stats['global_checkpoint'] | seq_no_stats['local_checkpoint']
-- | -- | -- | --
data | 04732dhl6os3icho60o30c1g | 1559739 | 1559766
data | 04732dhl6os3icho60o30c1g | 1559514 | 1559551
data | 04732dhl6os3icho60o30c1g | 1561929 | 1561975
data | 04732dhl6os3icho60o30c1g | 1559234 | 1559280
data | 04732dhl6os3icho60o30c1g | 1556494 | 1556525
data | 04732dhl6os3icho60o30c1g | 1560196 | 1560235

Also a lot of older partitions in the table are in warning or critical state and are not able to recover as it seams :(

Again I tried a couple of times the: `ALTER CLUSTER REROUTE RETRY FAILED` command. It looks like the warning partitions are solved by this, but there are multiple critical ones that don't resolve.

Health | Ident | Partition values - weeks | Configured replicas | Configured shards | Started shards | Missing shards | Underreplicated shards | Total records | Unavailable records | Underreplicated records | Size
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
critical | 04732dhg74rj2e1k60o30c1g | 1609718400000 | 1 | 6 | 10 | 1 | 1 | 8665387 | 1733078 | 3466155 | 1.8 GiB
good | 04732dhh60pj4cpi60o30c1g | 1610323200000 | 1 | 6 | 12 | 0 | 0 | 10444648 | 0 | 0 | 2.2 GiB
good | 04732dhh60sj4e1g60o30c1g | 1610928000000 | 1 | 6 | 12 | 0 | 0 | 10626677 | 0 | 0 | 2.2 GiB
good | 04732dhh64qj6cho60o30c1g | 1611532800000 | 1 | 6 | 12 | 0 | 0 | 11162430 | 0 | 0 | 2.3 GiB
good | 04732dhh68oj6dpm60o30c1g | 1612137600000 | 1 | 6 | 12 | 0 | 0 | 11011818 | 0 | 0 | 2.3 GiB
good | 04732dhh68rj8chk60o30c1g | 1612742400000 | 1 | 6 | 12 | 0 | 0 | 11489581 | 0 | 0 | 2.4 GiB
good | 04732dhh6cpj8dpi60o30c1g | 1613347200000 | 1 | 6 | 12 | 0 | 0 | 11187494 | 0 | 0 | 2.3 GiB
good | 04732dhh6csjachg60o30c1g | 1613952000000 | 1 | 6 | 12 | 0 | 0 | 11437306 | 0 | 0 | 2.4 GiB
good | 04732dhh6gqjadho60o30c1g | 1614556800000 | 1 | 6 | 12 | 0 | 0 | 11522008 | 0 | 0 | 2.4 GiB
good | 04732dhh6kojcc9m60o30c1g | 1615161600000 | 1 | 6 | 12 | 0 | 0 | 11715400 | 0 | 0 | 2.4 GiB
good | 04732dhh6krjcdhk60o30c1g | 1615766400000 | 1 | 6 | 12 | 0 | 0 | 11803192 | 0 | 0 | 2.5 GiB
good | 04732dhh6opjec9i60o30c1g | 1616371200000 | 1 | 6 | 12 | 0 | 0 | 11802529 | 0 | 0 | 2.4 GiB
good | 04732dhh6osjedhg60o30c1g | 1616976000000 | 1 | 6 | 12 | 0 | 0 | 12294851 | 0 | 0 | 2.6 GiB
good | 04732dhh6sqjgc1o60o30c1g | 1617580800000 | 1 | 6 | 12 | 0 | 0 | 12706337 | 0 | 0 | 2.7 GiB
good | 04732dhh70ojgd9m60o30c1g | 1618185600000 | 1 | 6 | 12 | 0 | 0 | 13149462 | 0 | 0 | 2.7 GiB
critical | 04732dhh70rjic1k60o30c1g | 1618790400000 | 1 | 6 | 10 | 1 | 1 | 11174379 | 2234876 | 4469752 | 2.3 GiB
good | 04732dhh74pjid9i60o30c1g | 1619395200000 | 1 | 6 | 12 | 0 | 0 | 13851918 | 0 | 0 | 2.9 GiB
good | 04732dhi60o30c1g60o30c1g | 1620000000000 | 1 | 6 | 12 | 0 | 0 | 15024261 | 0 | 0 | 3.2 GiB
critical | 04732dhi60r30d1o60o30c1g | 1620604800000 | 1 | 6 | 10 | 1 | 1 | 12414690 | 2482938 | 4965876 | 2.6 GiB
critical | 04732dhi64p30e9m60o30c1g | 1621209600000 | 1 | 6 | 10 | 1 | 1 | 12383654 | 2476731 | 4953462 | 2.6 GiB
good | 04732dhi64s32d1k60o30c1g | 1621814400000 | 1 | 6 | 12 | 0 | 0 | 15308105 | 0 | 0 | 3.2 GiB
critical | 04732dhi68q32e9i60o30c1g | 1622419200000 | 1 | 6 | 10 | 1 | 1 | 13922927 | 2784586 | 5569171 | 2.9 GiB

This way each time I restart the cluster I lose data, and then I need to restore partitions from the backup. This is not really a comforting idea.
