### ISSUE TITLE
CrateDB fails to start on Windows with -Cdiscovery.type=single-node

### ISSUE THREAD

**Issue by michaelkremmel** [crate/crate#18378]
### CrateDB version

latest

### CrateDB setup information

Running CrateDB on Docker on Windows as described in some of our tutorials, e.g.,  [Load data into CrateDB using Telegraf](https://cratedb.com/docs/guide/integrate/telegraf/tutorial.html), or [Load data from an MQTT topic into CrateDB](https://cratedb.com/docs/guide/integrate/mqtt/tutorial.html) with:
```
docker run --name=cratedb --rm -it --network=cratedb-demo --publish=4200:4200 --publish=5432:5432 --env=CRATE_HEAP_SIZE=2g docker.io/crate -Cdiscovery.type=single-node
```

### Problem description

CrateDB fails to start with this error message:
```
WARNING: Using incubator modules: jdk.incubator.vector
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "kvp.value" is null
        at io.crate.server.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:120)
        at org.elasticsearch.cli.Command.main(Command.java:86)
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:68)
```

### Steps to Reproduce

1. Start Docker on Windows
2. Open a terminal and paste the command as suggested in the tutorials: 
```
docker run --name=cratedb --rm -it --network=cratedb-demo --publish=4200:4200 --publish=5432:5432 --env=CRATE_HEAP_SIZE=2g docker.io/crate -Cdiscovery.type=single-node
```

### Actual Result

This is the error message:
```
WARNING: Using incubator modules: jdk.incubator.vector
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "kvp.value" is null
        at io.crate.server.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:120)
        at org.elasticsearch.cli.Command.main(Command.java:86)
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:68)
```

### Expected Result

That CrateDB starts successfully as it does without the `-Cdiscovery.type=single-node` parameter.

**Comment by matriv** [comment]
@michaelkremmel May I please ask you to try a couple of things?

1. Can you try to bootstrap crate from the [windows tarball](https://cdn.crate.io/downloads/releases/cratedb/x64_windows/crate-6.0.2.zip) using the `crate.bat` and add the `-Cdiscovery.type=single-node`?
2. Can you please try with docker but with a different parameter like `-Cstats.enabled=false` ?

thx!

**Comment by michaelkremmel** [comment]
@matriv Here are the results:

1. Running `crate.bat -Cdiscovery.type=single-node` I got a similar but not exactly the same error message:
`WARNING: Using incubator modules: jdk.incubator.vector
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "kvp.value" is null
        at io.crate.server.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:120)
        at org.elasticsearch.cli.Command.main(Command.java:86)
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:72)`
2. Running `docker run --name=cratedb --rm -it --network=cratedb-demo --publish=4200:4200 --publish=5432:5432 --env=CRATE_HEAP_SIZE=2g docker.io/crate -Cstats.enabled=false` I got the following error message:
`WARNING: Using incubator modules: jdk.incubator.vector
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "kvp.value" is null
        at io.crate.server.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:120)
        at org.elasticsearch.cli.Command.main(Command.java:86)
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:68)`

**Comment by matriv** [comment]
The issue comes from `Powershell`, please try the same (crate.bat, and docker) but from simple window's `cmd`.

**Comment by matriv** [comment]
@michaelkremmel another alternative to prevent PowerShell from doing funky stuff with the command line args is to pass them like:
```
docker run --name=cratedb --rm -it --network=cratedb-demo --publish=4200:4200 --publish=5432:5432 --env=CRATE_HEAP_SIZE=2g docker.io/crate '-Cdiscovery.type'='single-node'
```

**Comment by matriv** [comment]
The issue has been fixed and will be available with the next hotfix release.

**Comment by michaelkremmel** [comment]
@matriv Thank you very much for fixing the issue and also for providing the guidance, however I still receive error messages in PowerShell while CMD is working fine. 

**CMD**
1. Running `crate.bat -Cdiscovery.type=single-node` worked
2. Running `docker run --name=cratedb --rm -it --network=cratedb-demo --publish=4200:4200 --publish=5432:5432 --env=CRATE_HEAP_SIZE=2g docker.io/crate -Cstats.enabled=false` worked

**PowerShell**

1. Running the command you mentioned `docker run --name=cratedb --rm -it --network=cratedb-demo --publish=4200:4200 --publish=5432:5432 --env=CRATE_HEAP_SIZE=2g docker.io/crate '-Cdiscovery.type'='single-node'` still gives me an error message. Or should this only work properly after the next release?
2. Also running `docker run --name=cratedb --rm -it --network=cratedb-demo --publish=4200:4200 --publish=5432:5432 --env=CRATE_HEAP_SIZE=2g docker.io/crate '-Cstats.enabled'='false'` produced the same error message:

`WARNING: Using incubator modules: jdk.incubator.vector
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "kvp.value" is null
        at io.crate.server.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:120)
        at org.elasticsearch.cli.Command.main(Command.java:86)
        at io.crate.bootstrap.CrateDB.main(CrateDB.java:68)`

**Comment by amotl** [comment]
Hi ~~@michaelkremmel. The fix will be available with the next hotfix release. `docker.io/crate` currently doesn't include it.~~ @matriv: Thanks for fixing so swiftly, we are looking forward to verify GH-18520.

Edit: Sorry, I misread or omitted your alternative suggestions. If they don't work for @michaelkremmel, let's use vanilla incantations and wait for the hotfix release to be published?

**Comment by matriv** [comment]
@michaelkremmel Please test with tonights nightly, tomorrow (both tarball and docker).

**Comment by matriv** [comment]
I've tested it myself, so unfortunately my fix doesn't fix the docker issue :( but also I don't know how to fix it, we'd need to create separate or complex `crate.bat` script to accommodate for PowerShell. At least it has been fixed for simple `crate.bat` bootstrap (no docker).

The workaround for docker is to include each setting in single quotes:
docker run --name=cratedb --rm -it --network=cratedb-demo --publish=4200:4200 --publish=5432:5432 --env=CRATE_HEAP_SIZE=2g docker.io/crate '-Cdiscovery.type=single-node' '-Cstats.enabled=false'

So @amotl I'd like to ask you to add this note in the cratedb guide. Either recommend using `cmd` and not powershell, or the single quotes, or both. Many thx!

**Comment by michaelkremmel** [comment]
To confirm, the workaround for PowerShell with the Docker command @matriv shared above worked for me as well.
