### ISSUE TITLE
Update queries appending a string with named parameter throws exception

### ISSUE THREAD

**Issue by 0bp** [crate/crate#3734]
This works and appends 'abc' to the data column
```
$updateStmt = $this->dbh->prepare('update mytable set data = data || 'abc' where id = :id');
$updateStmt->execute(array(
    'id' => $id
));
```

Passing the string as named parameter fails:
```
$updateStmt = $this->dbh->prepare('update mytable set data = data || :data where id = :id');
$updateStmt->execute(array(
    'id' => $id,
    'data' => 'abc'
));
```

Same error with:
```
$updateStmt = $this->dbh->prepare('update mytable set data = concat(data, :data) where id = :id');
$updateStmt->execute(array(
    'id' => $id,
    'data' => 'abc'
));
```

Error:
```
Crate\PDO\Exception\PDOException: SQLActionException[Failed to parse source [{"stmt":"update mytable set data = data || ?  where id = ?","args":{"1":"...","0":"abc"}}]]

/Users/boris/Documents/Productsup/platform-api-crate-backend/vendor/crate/crate-pdo/src/Crate/PDO/PDO.php:121
/Users/boris/Documents/Productsup/platform-api-crate-backend/vendor/crate/crate-pdo/src/Crate/PDO/PDOStatement.php:208
/Users/boris/Documents/Productsup/platform-api-crate-backend/vendor/crate/crate-pdo/src/Crate/PDO/PDOStatement.php:208
```

**Comment by joemoe** [comment]
hi @0bp, we'll have a look at it. might be something that belongs to https://github.com/crate/crate-pdo but we'll see.

**Comment by mfussenegger** [comment]
Very likely a crate-pdo issue

```
🐘   http localhost:4200/_sql stmt="select ? || '_abc' from sys.cluster" args:='["foobar"]'
HTTP/1.1 200 OK
Content-Length: 88
Content-Type: application/json; charset=UTF-8

{
    "cols": [
        "concat($1, '_abc')"
    ],
    "duration": 4.198138,
    "rowcount": 1,
    "rows": [
        [
            "foobar_abc"
        ]
    ]
}
```

Judging from the error the args are passed in a invalid format:

``` "args":{"1":"...","0":"abc"} ```

It should be a list and not a dictionary

**Comment by 0bp** [comment]
@mfussenegger in your example you're doing select concat, which works on my end as well but it doesn't work on update queries appending an already existing value.

\Crate\PDO\Http\Server::doPost still as an array:
```
array(4) {
  'json' =>
  array(2) {
    'stmt' =>
    string(56) "update mytable set data = data || ?  where batch_id = ?"
    'args' =>
    array(2) {
      [1] =>
      string(32) "e46de7e1bcaaced9a54f1e9d0d2f800d"
      [0] =>
      string(3) "abc"
    }
  }
```

So, it's either a crate/crate issue or the error message output.

**Comment by 0bp** [comment]
Just noticed the array order which is a bit odd. So I tried to reorder the parameters:
```
$updateStmt->execute(array(
    'id' => $id,
    'data' => 'abc'
));
```

**Comment by mikethebeer** [comment]
Hi @0bp,

the issue was in the PDO driver. I have fixed the issue now in master https://github.com/crate/crate-pdo/commit/533f37475c7654ddeda557ad413b6ff1b148adb0. This fix will be in the hotfix release of version 5.1.

Cheers,
Michael

**Comment by 0bp** [comment]
Thanks!

But it's fixed for that particular case only. If you do
```
update mytable set field = concat(field, :field) where id = :id and otherfield != :field
```
where you can't control the order of parameters because you're using them twice, it still fails. in that case the args look like this:
```
"args":{"1":"e46de7e1bcaaced9a54f1e9d0d2f800d","2":"abc"}}
```

**Comment by joemoe** [comment]
thanks @0bp, will fix that also. sorry for not doing it in the first place.
