### ISSUE TITLE
SQLActionException[IndexOutOfBoundsException: Index: 0, Size: 0]

### ISSUE THREAD

**Issue by kanarelo** [crate/crate#8112]
**CrateDB version**: 3.2.0

**Environment description**:
java version "1.8.0_181" Oracle Corporation OpenJDK 64-Bit Server VM (build 25.181-b13)
Using the docker image crate/crate:3.2.0
Docker version: 18.09.1, build 4c52b90

**Problem description**:
I get the error:
```SQLActionException[IndexOutOfBoundsException: Index: 0, Size: 0]```
when I run the following SQL below;

**Steps to reproduce**:
This is related to: #8103

```sql
SELECT DISTINCT
  "location_country", 
  COUNT("location_country") AS "no_of_plays" 
FROM "voxsnap"."events_2018" 
WHERE (
  "customer" = 'acustomerid' AND 
    (
      "event_type" = 'play' OR 
       "event_type" = 'alexaplay' OR 
       "event_type" = 'podcastplay'
    ) 
  AND "location_country" IS NOT NULL
) 
GROUP BY "events_2018"."location_country" 
ORDER BY "events_2018"."location_country" ASC;
```

**Comment by kanarelo** [comment]
But if I do:

```
SELECT DISTINCT
  "location_country", 
  COUNT(*) AS "no_of_plays" 
FROM "voxsnap"."events_2018" 
WHERE (
  "customer" = 'acustomerid' AND 
    (
      "event_type" = 'play' OR 
       "event_type" = 'alexaplay' OR 
       "event_type" = 'podcastplay'
    ) 
  AND "location_country" IS NOT NULL
) 
GROUP BY "events_2018"."location_country" 
ORDER BY "events_2018"."location_country" ASC;
```

it works...

**Comment by mfussenegger** [comment]
I tried to reproduce the issue, but for me both queries work. I used the schema provided in the other issue and generated a couple of random records.

Could you post the stack trace of the error as well (launching `crash` with `--verbose` or toggle it inside the repl with `\verbose`)

**Comment by kanarelo** [comment]
Fixed in new update

**Comment by MANUDUBEY1992** [comment]
Crate Version: 3.1.4
java version "1.8.0_181" Oracle Corporation OpenJDK 64-Bit Server VM (build 25.181-b13)
Similar Issue : Stacktrace is following

```
SQLActionException[IndexOutOfBoundsException: Index: 1, Size: 1]
SQLActionException: 500 Internal Server Error 5000 IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at io.crate.expression.InputRow.get(InputRow.java:47)
	at io.crate.execution.engine.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:38)
	at io.crate.execution.engine.collect.InputCollectExpression.setNextRow(InputCollectExpression.java:26)
	at io.crate.execution.engine.collect.GroupByOptimizedIterator.applyAggregatesGroupedByKey(GroupByOptimizedIterator.java:286)
	at io.crate.execution.engine.collect.GroupByOptimizedIterator.lambda$tryOptimizeSingleStringKey$3(GroupByOptimizedIterator.java:180)
	at io.crate.data.CollectingBatchIterator.loadNextBatch(CollectingBatchIterator.java:135)
	at io.crate.data.CloseAssertingBatchIterator.loadNextBatch(CloseAssertingBatchIterator.java:69)
	at io.crate.data.AsyncCompositeBatchIterator.lambda$loadNextBatch$1(AsyncCompositeBatchIterator.java:131)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RomanGorbatko** [comment]
> Fixed in new update

I still have this issue in 4.0.0 version.

Have `SQLActionException[IndexOutOfBoundsException: Index 0 out of bounds for length 0]` error:
```
select count(p.funnelid) purchases, p.funnelid funnelid
from purchases p
where p.contactid = 'f952b1f8-288a-4c73-a08c-76b789d703e9' and p.transactionstatus = 5 and p.funnelid is not null
group by p.funnelid
```

Works well:
```
select count(1) purchases, p.funnelid funnelid
from purchases p
where p.contactid = 'f952b1f8-288a-4c73-a08c-76b789d703e9' and p.transactionstatus = 5 and p.funnelid is not null
group by p.funnelid
```

**Comment by mfussenegger** [comment]
@RomanGorbatko could you also post the schema of your tables?

**Comment by RomanGorbatko** [comment]
@mfussenegger  
```SQL
CREATE TABLE IF NOT EXISTS "stat"."purchases"
(
	"id" string,
	"revisionid" string, /* uuid funnels.revisions */
	"userid" String, /* uuid users.users */
	"contactid" String, /* UUID|nullable contacts.contacts */
	"sourceid" String, /* UUID funnels.sources */
	"upgradeid" String,
	"paymentsystem" String,
	"trackingkey" String,
	"invoiceurl" String,
	"orderdetailsurl" String,
	"productname" String, /* UUID funnels.products */
	"productid" String, /* UUID funnels.products */
	"producttype" Integer, /* Enum8( 'main' = 1, 'upsell' = 2, 'downsell' = 3 ), */
	"productcost" Double,
	"productcurrency" String,
	"quantity" Integer,
	"amount" Double,
	"transactionid" String, /* UUID */
	"transactiontype" Integer, /* Enum8( 'single_payment' = 1, 'subscription' = 2, 'installment' = 3 ), */
	"transactionstatus" Integer, /* Enum8( 'paying' = 1, 'aborted' = 2, 'unpaid' = 3, 'reminding' = 4, 'completed' = 5 ), */
	"transactiondate" Timestamp,
	"vatamount" Double,
	"vatrate" String,
	"geocountry" string,
	"eventdate" Timestamp,
	"stepid" string, /* uuid funnels.steps */
	"prevstepid" string, /* uuid funnels.steps */
	"prevsteptype" integer, /* uuid funnels.steps */
	"funnelid" string, /* uuid funnels.funnels */
	"pageid" string, /* uuid funnels.pages */
	"prevpageid" string, /* uuid funnels.pages */
	"steptype" integer, /* variations simple */
	"funneltype" integer, /* variations detailed */
	"paymentlogid" string, /* variations detailed */
	"isreply" boolean
);
```

**Comment by mfussenegger** [comment]
@RomanGorbatko 

1) Do you run this on a single node or a cluster with mulitple nodes?
2) Could you also run the same query again with `verbose` enabled and post the stacktrace? (inside crash `\verbose` or in the admin-ui check the `show error trace` option.
3) Could you also run the following query and post the output of that?

```
EXPLAIN
SELECT
    count(p.funnelid) purchases,
    p.funnelid funnelid
FROM
    stat.purchases p
WHERE
    p.contactid = 'f952b1f8-288a-4c73-a08c-76b789d703e9'
    AND p.transactionstatus = 5
    AND p.funnelid IS NOT NULL
GROUP BY
    p.funnelid;
```
